apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  annotations:
    serverless.openshift.io/default-enable-http2: "true"
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    features:
      kubernetes.podspec-init-containers: enabled # this is only necessary for adding artificial startup-delays
