# Copyright 2022 The Knative Authors..
# SPDX-License-Identifier: Apache-2.0

# This file is automagically synced here from github.com/knative-extensions/knobots

name: Test

on:
  push:
    branches: [ 'main', 'release-*' ]

  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  test:
    uses: massongit/actions/.github/workflows/reusable-go-test.yaml@massongit-patch-1
